name: Commit Tasks

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Run mvn test
        run: mvn test
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Codespell
        run: pip install codespell
      - name: Check spelling
        run: codespell -S=".git"
  check-for-non-lettuce-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Download script
        env:
          SCRIPT_URL: ${{ secrets.IMPORT_TEST_SCRIPT_URL }}
        run: curl $SCRIPT_URL -o 'importscript.py'
      - name: Run script
        run: python ./importscript.py
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy bot
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        run: "curl -s -f -X POST -H \"Authorization: $DEPLOY_KEY\" -m 45 $DEPLOY_URL"
