name: Commit Tasks

on:
  push:
    paths:
      - '**.java'
      - 'pom.xml'
  pull_request:
    types:
    - closed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '18'
      - name: Run mvn test
        run: mvn test
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Codespell
        run: pip install codespell
      - name: Check spelling
        run: codespell -S=".git"
  check-for-non-lettuce-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Download script
        env:
          SCRIPT_URL: ${{ secrets.IMPORT_TEST_SCRIPT_URL }}
        run: curl $SCRIPT_URL -o 'importscript.py'
      - name: Run script
        run: python ./importscript.py
  deploy:
    if: "${{ !contains(github.event.head_commit.message, '[nodeploy]') && github.ref == 'refs/heads/master' && github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' && github.event.pull_request.merged == true }}"
    runs-on: ubuntu-latest
    needs: [test, check-for-non-lettuce-imports, check-spelling]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '18'
      - name: Prepare files
        env:
          CONFIG_DATA: ${{ secrets.CONFIG_DATA }}
        run: "printf \"$CONFIG_DATA\" > $GITHUB_WORKSPACE/src/main/java/com/cominatyou/Config.java"
      - name: Build jar
        run: mvn clean compile assembly:single
      - name: Deploy bot
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        run: "curl -s -f -X POST -T $GITHUB_WORKSPACE/target/hildabot-*.jar -H \"Authorization: $DEPLOY_KEY\" -H \"Content-Type: application/octet-stream\" -m 30 $DEPLOY_URL"
