name: Commit Tasks (Non-Master)

on:
  push:
    branches-ignore:
      - 'master'
    paths:
      - '**.java'
      - 'pom.xml'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'
      - name: Run mvn test
        run: mvn test
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Codespell
        run: pip install codespell
      - name: Check spelling
        run: codespell -S=".git"
  check-for-non-lettuce-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Download script
        env:
          SCRIPT_URL: ${{ secrets.IMPORT_TEST_SCRIPT_URL }}
        run: curl $SCRIPT_URL -o 'importscript.py'
      - name: Run script
        run: python ./importscript.py
